/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.st_project_fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import static javax.swing.UIManager.getInt;





/**
 *
 * @author gsudi
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }
    
    int id = 0;
    int getId()
    {
        ResultSet rs = null;
        try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
          String url = "jdbc:mysql://localhost:3306/fees__management_db?zeroDateTimeBehavior=CONVERT_TO_NULL";
          Connection con = DriverManager.getConnection(url,"root","Sudin@7585");
          String sql = "select max(id) from signup";
          Statement st = con.createStatement();
          rs = st.executeQuery(sql);
          while(rs.next())
          {
             id = rs.getInt(1);
             id++;
          }
        }
        
        catch(Exception e)
        {
            
            e.printStackTrace();
        }
        
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtcpfield = new javax.swing.JPasswordField();
        txtfname = new javax.swing.JTextField();
        txtmnumber = new javax.swing.JTextField();
        txtpfield = new javax.swing.JPasswordField();
        txtlname = new javax.swing.JTextField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnsignup = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblcpassworderror = new javax.swing.JLabel();
        lblpassworderror = new javax.swing.JLabel();
        lblmnubererror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Sign Up");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Mobile No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("D.O.B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, 20));

        txtuname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 190, 30));

        txtcpfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtcpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 190, 30));

        txtfname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 190, 30));

        txtmnumber.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtmnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmnumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtmnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 190, 30));

        txtpfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfieldKeyTyped(evt);
            }
        });
        getContentPane().add(txtpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 190, 30));

        txtlname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 190, 30));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, 30));

        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsignup.setText("Signup");
        btnsignup.setActionCommand("Login");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 100, 40));

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 100, 40));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 100, 40));

        lblcpassworderror.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblcpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 220, 20));

        lblpassworderror.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 246, 230, 20));

        lblmnubererror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblmnubererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 230, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
validation();
if(validation())
{
    insertData();
}
else
{
 JOptionPane.showMessageDialog(this,"Validation Issue.");
}
       
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
      Login l1 = new Login();
      l1.show();
      this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
    txtfname.setText("");
    txtlname.setText("");
    txtuname.setText("");
    txtpfield.setText("");
    txtcpfield.setText("");
    //dob=txtdob.getDate();
    txtmnumber.setText("");
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtpfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyPressed
passwordCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyPressed

    private void txtpfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyReleased
passwordCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyReleased

    private void txtpfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyTyped
passwordCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyTyped

    private void txtmnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnumberKeyPressed
mobileCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnumberKeyPressed

    private void txtmnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnumberKeyReleased
mobileCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnumberKeyReleased

    private void txtmnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnumberKeyTyped
mobileCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnumberKeyTyped
    String fname,lname,uname,password,cpassword,mnumber;
    Date dob;
    
    void insertData()
    {
        SimpleDateFormat s1 = new SimpleDateFormat("yyyy-MM-dd");
        String dob1 = s1.format(dob);
        try
        {
          Class.forName("com.mysql.cj.jdbc.Driver");
          String url = "jdbc:mysql://localhost:3306/fees__management_db?zeroDateTimeBehavior=CONVERT_TO_NULL";
          Connection con = DriverManager.getConnection(url,"root","Sudin@7585");
          
          String sql = "insert into signup values(?,?,?,?,?,?,?)";
                            PreparedStatement st = con.prepareStatement(sql);
                            
                            st.setInt(1, getId());
                            st.setString(2, fname);
                            st.setString(3, lname);
                            st.setString(4, uname);
                            st.setString(5, password);
                            st.setString(6, dob1);
                            st.setString(7, mnumber);
                            int i = st.executeUpdate();
                            if(i>0)
                            {
                               JOptionPane.showMessageDialog(this,"Record Inserted Succesfully"); 
                            }
                            else
                            {
                             JOptionPane.showMessageDialog(this,"Record Not Inserted Succesfully");
                            }
        }
        catch(Exception e)
        {
           e.printStackTrace();
        }
    }
    
    boolean validation()
    {
    fname=txtfname.getText();
    lname=txtlname.getText();
    uname=txtuname.getText();
    password=txtpfield.getText();
    cpassword=txtcpfield.getText();
    dob=txtdob.getDate();
    mnumber=txtmnumber.getText();
    
    if(fname.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Please Enter First Name...");
    return false;
    }
    
    if(lname.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Please Enter Last Name...");
    return false;
    }
    
    if(uname.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Please Enter User Name...");
    return false;
    }
    
    if(password.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Piease Enter Password...");
    return false;
    }
    
    if(cpassword.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Piease Enter Confirm Password...");
    return false;
    }
    
    if(mnumber.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Please Enter Mobile Number...");
    return false;
    }
    
    if(dob.equals(null))
    {
    JOptionPane.showMessageDialog(this,"Piease Enter Date of Birth...");
    return false;
    }
    
    return true;
    }
    
    void passwordCheck()
    {
       password=txtpfield.getText(); 
       
       if(password.length()>=8)
       {
        lblpassworderror.setText("");
       }
       
       else
       {
           lblpassworderror.setText("Enter 8 Digit Password");
       }
       
    }
    
    void mobileCheck()
    {
        mnumber=txtmnumber.getText();
        
        if(mnumber.length()==10)
        {
         lblmnubererror.setText("");
        }
        else
        {
            lblmnubererror.setText("Enter 10 digit Mobile Number.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcpassworderror;
    private javax.swing.JLabel lblmnubererror;
    private javax.swing.JLabel lblpassworderror;
    private javax.swing.JPasswordField txtcpfield;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmnumber;
    private javax.swing.JPasswordField txtpfield;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
